[package]
name = "delix"
version = "0.1.0"
authors = ["Philipp Br√ºll <bruell@simia.tech>"]

[dependencies]
byteorder = "0.4"
getopts = "0.2"
chunked_transfer = "0.3"
hyper = "0.7"
log = "0.3"
protobuf = "1.0"
rand = "0.3"
rust-crypto = "0.2"
rustc-serialize = "0.3"
time = "0.1"
toml = "0.1"
